  services:
    db:
      image: postgres:15
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres2508
        POSTGRES_DB: vetclinic_db
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
      restart: always
      networks:
        - app-network

    auth1:
      build: ./backend/auth_service
      container_name: auth_service_1
      restart: always
      environment:
        - PORT=5001
        - DATABASE_URL=postgresql://postgres:postgres2508@db:5432/vetclinic_db
      expose:
        - "5001"
      depends_on:
        db:
          condition: service_healthy
      networks:
        - app-network

    auth2:
      build: ./backend/auth_service
      container_name: auth_service_2
      restart: always
      environment:
        - PORT=5002
        - DATABASE_URL=postgresql://postgres:postgres2508@db:5432/vetclinic_db
      expose:
        - "5002"
      depends_on:
        db:
          condition: service_healthy
      networks:
        - app-network

    main1:
      build: ./backend/main_service
      container_name: main_service_1
      restart: always
      environment:
        - PORT=5000
        - DATABASE_URL=postgresql://postgres:postgres2508@db:5432/vetclinic_db
        - AUTH_SERVICE_URL=http://auth1:5001
      expose:
        - "5000"
      depends_on:
        db:
          condition: service_healthy
        auth1:
          condition: service_started
        auth2:
          condition: service_started
      networks:
        - app-network

    main2:
      build: ./backend/main_service
      container_name: main_service_2
      restart: always
      environment:
        - PORT=5004
        - DATABASE_URL=postgresql://postgres:postgres2508@db:5432/vetclinic_db
        - AUTH_SERVICE_URL=http://auth1:5001
      expose:
        - "5004"
      depends_on:
        db:
          condition: service_healthy
        auth1:
          condition: service_started
        auth2:
          condition: service_started
      networks:
        - app-network

    frontend:
      build: ./frontend
      container_name: frontend
      ports:
        - "5173:5173"
      networks:
        - app-network
      environment:
        - VITE_API_URL=http://localhost:80
        - NODE_ENV=production
      restart: unless-stopped

    nginx:
      build: ./nginx
      container_name: nginx_balancer
      restart: always
      ports:
        - "80:80"
        - "443:443"

      depends_on:
        - auth1
        - auth2
        - main1
        - main2
        - frontend
      networks:
        - app-network

  networks:
    app-network:
      driver: bridge

  volumes:
    postgres_data:
